### PR TITLE
Bug fix for LDD generation when an attribute is not exposed in the core IM

### LINKED ISSUE #797: GEOM LDD schematron rules are not executing as expected `<kernel_type>` validation
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

Validate is passing labels that contain an incorrect kernel_type. E.g. [this label](https://pds-rings.seti.org/pds4/bundles/uranus_occs_earthbased/uranus_occ_u5_lco_250cm/data/rings/u5_lco_250cm_2200nm_counts-v-time_rings_egress.xml):
```
                    <geom:SPICE_Kernel_Identification>
                        <geom:kernel_type>BPC</geom:kernel_type>
                        <geom:spice_kernel_file_name>earth_720101_031229.bpc</geom:spice_kernel_file_name>
                    </geom:SPICE_Kernel_Identification>
                    <geom:SPICE_Kernel_Identification>
```

However, the [Geometry dictionary](https://github.com/pds-data-dictionaries/ldd-geom/blob/main/src/PDS4_GEOM_IngestLDD.xml) uses `pds:kernel_type` not `geom:kernel_type` – there is no definition of `kernel_type` within the Geom dictionary, and the [`SPICE_Kernel_Identification` class](https://github.com/pds-data-dictionaries/ldd-geom/blob/cfe3426d2515073aaf26a5eabcbb50dc5476c269/src/PDS4_GEOM_IngestLDD.xml#L5799) includes `pds.kernel_type` as a member.  The change log says that this change from `kernel_type` to `pds:kernel_type` was made back in 2015. 

The [schematron](https://github.com/pds-data-dictionaries/ldd-geom/blob/main/build/release/1.B.1.0/PDS4_GEOM_1B10_1700.sch) states:
```
  <sch:pattern>
    <sch:rule context="geom:SPICE_Kernel_Identification/pds:kernel_type">
      <sch:assert test=". = ('CK', 'DBK', 'DSK', 'EK', 'FK', 'IK', 'LSK', 'MK', 'PCK', 'SCLK', 'SPK')">
        The attribute pds:kernel_type must be equal to one of the following values 'CK', 'DBK', 'DSK', 'EK', 'FK', 'IK', 'LSK', 'MK', 'PCK', 'SCLK', 'SPK'.</sch:assert>
    </sch:rule>
  </sch:pattern>
```

Isn't Validate incorrect to allow the call to `geom:kernel_type`? It’s not a valid member of the class so it should trigger a structural error (not a schematron error).

Alternatively, if it was reasonable for Validate to interpret `geom:kernel_type` as if it were `pds:kernel_type`, then it should have rejected "BPC" as a value because it is not part of the enumerated list. 

### 🕵️ Expected behavior

I expected Validate to flag an error for `<geom:kernel_type>BPC</geom:kernel_type>`

### 📜 To Reproduce

–`validate-3.5.0-SNAPSHOT/bin/validate <path/to/bundle> -R pds4.bundle -v 2 -r validate_report.log`

### 🖥 Environment Info

- Operating System: MacOS 10.15.7

### 📚 Version of Software Used

- Version 3.5.0-SNAPSHOT
Release Date: 2024-03-06 21:32:16

### 🩺 Test Data / Additional context

Example label linked above (see [bundleset](https://pds-rings.seti.org/pds4/bundles/uranus_occs_earthbased))

### 🦄 Related requirements

_No response_

### ⚙️ Engineering Details

It looks like the GEOM schema expects geom:SPICE_Kernel_Identification/geom:kernel_type (as expected), but the schematron generation does not correctly translate the pds:kernel_type type into the geom: namespace.

Changing the schematron xpath from `pds:kernel_type` to `geom:kernel_type`, like it should be, modifying the XML example above in to a local version of the schematron, and it now throws an error for a bad value like it should be doing.

image

It looks like this may be specific to when an attribute is re-used from the core namespace:
 
```xml
        <DD_Association>
            <identifier_reference>pds.kernel_type</identifier_reference>
            <reference_type>attribute_of</reference_type>
            <minimum_occurrences>0</minimum_occurrences>
            <maximum_occurrences>1</maximum_occurrences>
        </DD_Association>
```

The issue identified is `pds.kernel_type` is not exposed by the core namespace. LDDTool should be raising an error, but instead, mistakenly puts the disconnected references in the schema/schematron, causing the bug noted above.

### 🎉 Integration & Test

_No response_

### PR DESCRIPTION
**Pull request by jshughes**
Modified LDDTool to expose Common (pds) attributes in the Common schema that are referenced by an LDD. Added error and warning messages for common attributes that are not exposed but referenced by an LDD. 

## 🗒️ Summary

The source of the problem is that attributes in the common (pds) schema that are referenced by an LDD had not been exposed. The referenced attributes used by the geom LDD are now being exposed in the Common schema. 

_To "expose" an attribute is to define the attribute using "xs:element" so that it can be referenced instead of redefined. Both approaches have been used since the release of V1.0.0.0. A problem exists only when the referenced attribute is not exposed but has standard values that must be validated by a schematron rule._

In addition LDDTool will now throw an Error for a referenced attribute that is not exposed but that has standards values.- (e.g., kernel_type) 

Alternatively LDDTool will throw a Warning for a referenced attribute that is not exposed but that does not have standard values. (e.g., name, description, ...)

Impact Note: The change to exposed all common attributes referenced by the geom LDD does result in a change to the LDD schema. This schema change should not have any impact but needs vetting. Specifically the attributes are now defined using a "ref" instead of a "name/type" in the definition. For example: the following statement: 
<xs:element name="kernel_type" type="pds:kernel_type" minOccurs="1" maxOccurs="1"> </xs:element>
 is now written as:
<xs:element ref="pds:kernel_type" minOccurs="0" maxOccurs="1"> </xs:element>.

@rsjoyner  should also review this change and its impact since both the common and LDD schemas are impacted. This release of LDDTool will require the new Common schema to eliminate the new warning messages.

This push also includes some additional cleanup. The Java methods Integer.parseInt() and Integer.valueOf() have replaced dated code that tests and converts numeric strings to integers.

## ⚙️ Test Data and/or Report
The attache zip file contains the new pds schema, geo schema, and a log showing warning and error messages when the referenced attributes are not exposed.
Example:
>>> ERROR Attribute:  - The referenced enumerated attribute pds.kernel_type must be exposed.
>>> WARNING Attribute:  - The referenced attribute pds.comment is not exposed.

Resolves #797 
[KernelType.zip](https://github.com/user-attachments/files/16385007/KernelType.zip)

### CODE REVIEW

**Comment by jordanpadams** [comment]
@jshughes I'm not sure this actually fixes the problem. I added some test data to `model-lddtool/src/test/resources/github797`, more specifically, you should be able to open up `test_label1_FAIL.xml` in Oxygen and see the issue.

It looks like by using `ref`, the attributes are now expected to be `pds:comment`, `pds:kernel_type`, etc. in the labels, which is a HUGE change from previous ways of specifying this type of information. I seem to remember we jumped back and forth on this many users ago, and landed on these attributes being "inherited" by the current namespace, e.g. `geom:comment`, `geom:kernel_type`, etc., not directly referenced.

Screenshot 2024-08-01 at 1 47 49 PM

Even if this is technically the way we should be doing it, I don't think we can introduce such a significant change in the schemas. Instead, I would think we would want to simply change this in the schematron:

Was:
```xml
<sch:rule context="geom:SPICE_Kernel_Identification/pds:kernel_type">
```
Should be:
```xml
<sch:rule context="geom:SPICE_Kernel_Identification/geom:kernel_type">
```

The specific test case I included should fail because `//geom:SPICE_Kernel_Identification/geom:kernel_type` is invalid in 2 places in the label.

**Comment by jordanpadams** [comment]
@jshughes this is what I expect to see:

Screenshot 2024-08-01 at 2 23 24 PM

**Comment by jordanpadams** [comment]
@jshughes note: be sure to pull the latest on this branch. main has been merged into it, so it contains all the test updates

**Comment by jshughes** [comment]
> It looks like by using ref, the attributes are now expected to be pds:comment, pds:kernel_type, etc. in the labels, which is a HUGE change from previous ways of specifying this type of information. I seem to remember we jumped back and forth on this many users ago, and landed on these attributes being "inherited" by the current namespace, e.g. geom:comment, geom:kernel_type, etc., not directly referenced.

I am including @rsjoyner for his input, if desired.

I agree and was concerned about the large number of changes that appeared in the LDD schema even though there should be no functional impact to the labels.  I am OK with going back to the redefinition of these elements in the LDD instead of referencing their definitions in Common. I will remove pds.name, pds.comment, and etc from the Common "exposed" list and remove the warning message for non-enumerated attributes that are being redefined.

I am still working the remaining kernel_type issue(s).

**Comment by jordanpadams** [comment]
@jshughes per this comment:

> I agree and was concerned about the large number of changes that appeared in the LDD schema even though there should be no functional impact to the labels. I am OK with going back to the redefinition of these elements in the LDD instead of referencing their definitions in Common. I will remove pds.name, pds.comment, and etc from the Common "exposed" list and remove the warning message for non-enumerated attributes that are being redefined.

I am OK with those being exposed since I think they are referenced a lot in Discipline LDDs, and the fact that the schemas or schematrons change do not really matter to me. What really matters is the label now expects `pds:comment` and `pds:kernel_type`, not the expected `geom:comment` and `geom:kernel_type`

**Comment by jshughes** [comment]
@rsjoyner  Ron was able to track down the problem that was bothering me. 

Background: The attribute pds:kernel_type is now exposed in the common schema. LDDTool subsequently include “pds:kernel_type” in both the geom schema and schematron files. The question was, why does the geom xml insert have “geom:kernel_type” when the schema used to create the xml insert uses "pds:kernel"?

The answer is that there was no import for the common (pds) namespace when creating the product label and the geometry xml insert.

In the following snippets the declaration "xmlns:pds="http://pds.nasa.gov/pds4/pds/v1" is included in the first snippet but missing in the second. 

-- pds:kernel -- 
<Product_Observational xmlns="http://pds.nasa.gov/pds4/pds/v1"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xmlns:pds="http://pds.nasa.gov/pds4/pds/v1" 
 xmlns:geom="http://pds.nasa.gov/pds4/geom/v1"
 xmlns:rings="http://pds.nasa.gov/pds4/rings/v1"
 xsi:schemaLocation="http://pds.nasa.gov/pds4/pds/v1 PDS4_PDS_1N00.xsd
                     http://pds.nasa.gov/pds4/geom/v1 PDS4_GEOM_1N00_1970.xsd
                     http://pds.nasa.gov/pds4/rings/v1 https://pds.nasa.gov/pds4/rings/v1/PDS4_RINGS_1E00_1A00.xsd">

-- geom:kernel -- 
<Product_Observational xmlns="http://pds.nasa.gov/pds4/pds/v1"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xmlns:geom="http://pds.nasa.gov/pds4/geom/v1"
 xmlns:rings="http://pds.nasa.gov/pds4/rings/v1"
 xsi:schemaLocation="http://pds.nasa.gov/pds4/pds/v1 https://pds.nasa.gov/pds4/pds/v1/PDS4_PDS_1E00.xsd
                     http://pds.nasa.gov/pds4/geom/v1 https://pds.nasa.gov/pds4/geom/v1/PDS4_GEOM_1B10_1700.xsd

**Comment by jordanpadams** [comment]
copy that. Thanks @jshughes

**Comment by jordanpadams** [comment]
@jshughes I will merge this. I am interested to see the ramifications here with other data providers.

**Review by jordanpadams — APPROVED** [review]

**Pull request merged**
