### PR TITLE
Fix validate misbehavior in cucumber tests

### LINKED ISSUE #822: Tests fail when there are multiple tests with multiple schemas/schematrons
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

When I try to run back to back tests calling validate, it does not pick up later specified schemas.

### 🕵️ Expected behavior

I expected the tests to run successfully.

### 📜 To Reproduce

Playing around with the `validate.feature` file.

### Scenario 1
* Execute as is
* First and last test fail (first test shouldn't pass)

### Scenario 2
* Comment out test 1 (github795)
* github797 fails when it should pass. Per the error, validate is not correctly reading the LDDs (Error refers to unrecognized `geom:Geometry`)

### Scenario 3
* Comment out test 1 (github795)
* Swap github795b and github797 in order
* All tests pass

### 🖥 Environment Info

```bash
MacOSx
```

### 📚 Version of Software Used

Latest snapshot

### 🩺 Test Data / Additional context

See repo

### 🦄 Related requirements

_No response_

### ⚙️ Engineering Details

No idea what is happening here. It appears validate is not properly reading/loading the GEOM LDD on the second run.

per comments below, blocked by https://github.com/NASA-PDS/validate/issues/1028

### 🎉 Integration & Test

_No response_

### PR DESCRIPTION
**Pull request by al-niessner**
## 🗒️ Summary
Check for internal errors and use latest validate

## ⚙️ Test Data and/or Report
See automated unit testing below or run cucumber tests if not automated yet.

## ♻️ Related Issues
Closes #822

### CODE REVIEW

**Comment by al-niessner** [comment]
@jordanpadams waiting for review on NASA-PDS/validate#1057 to see if it fixes this problem. Using validate project for this instead of maven artifact in eclipse makes a giant mess as it tries to run both cucumbers simultaneously then complains about it. So I need the latest validate artifact.

**Comment by al-niessner** [comment]
@jordanpadams @nutjob4life @tloubrieu-jpl 

All tests work now. I had to re-enable one of the tests validate.feature tests, but they all work independently as they do together. The schema(tron) mole (le Carre style) was the culprit here too.

**Comment by al-niessner** [comment]
Is this a weird problem where the github actions is not pulling the very latest snapshot because it thinks it already has it?

**Comment by nutjob4life** [comment]
@al-niessner yes it is; do you have a link to the GitHub Actions run?

**Comment by al-niessner** [comment]
@nutjob4life 

I do not understand the question, so no. I can click on details and ask it to run all jobs again. I did that and it seems to have made them all pass. Or an angel did something for me that I will never ask about. Exactly why you teach people to fish not give them a fish.

**Comment by nutjob4life** [comment]
@al-niessner hey I'm happy not to look the gift horse in the mouth—whatever that means! Let's press on!

**Review by jordanpadams — APPROVED** [review]

**Pull request merged**
