### PR TITLE
Issue #650 invalid modification date for ld ds for versions 1 h00 and earlier

### LINKED ISSUE #650: Invalid `modification_date` for LDDs for versions 1H00 and earlier
### Checked for duplicates

No - I haven't checked

### 🐛 Describe the bug

When I generated an LDD for 1H00 and 1G00 and validated the output label, I am getting a schematron validation failure.

### 🕵️ Expected behavior

I expected the `Product_XML_Schema` to validate successfully.

### 📜 To Reproduce

1. generate the LDD with a PDS4 version <= 1H00 e.g.
```
$ lddtool -lp -V 1H00 src/PDS4_LRO_IngestLDD.xml
```

2. then validate the label
```
$ validate -t PDS4_LRO_1H00_1021.xml
...
Product Level Validation Results

  FAIL: file:/Users/jpadams/proj/pds/pdsen/workspace/validate/ldd-lro/PDS4_LRO_1H00_1021.xml
      ERROR  [error.label.schema]   line 20, 36: cvc-pattern-valid: Value '2023-04-10T14:00:49' is not facet-valid with respect to pattern '(-)?[0-9]{4}(Z?)|(-)?[0-9]{4}-((0[1-9])|(1[0-2]))(Z?)|(-)?[0-9]{4}-((0[1-9])|(1[0-2]))-((0[1-9])|([1-2][0-9])|(3[0-1]))(Z?)' for type 'modification_date'.
      ERROR  [error.label.schema]   line 20, 36: cvc-type.3.1.3: The value '2023-04-10T14:00:49' of element 'modification_date' is not valid.
...
```

Successful validation with 1I00:
```
$ validate -t PDS4_LRO_1I00_1021.xml
...
Product Level Validation Results

  PASS: file:/Users/jpadams/proj/pds/pdsen/workspace/validate/ldd-lro/PDS4_LRO_1I00_1021.xml
        1 product validation(s) completed
...
```

### 🖥 Environment Info

- Operating System: MacOSX

### 📚 Version of Software Used

v14.2.1

### 🩺 Test Data / Additional context

https://raw.githubusercontent.com/pds-data-dictionaries/ldd-lro/main/src/PDS4_LRO_IngestLDD.xml

### 🦄 Related requirements

_No response_

### ⚙️ Engineering Details

_No response_

### PR DESCRIPTION
**Pull request by jshughes**
Issue #650 Invalid modification_date for LDDs for versions 1H00 and earlier 
				
Changed the value written for <modification_date> from masterTodaysDateTimeUTCwT to masterTodaysDateUTC, i.e., use the Date and not the DateTime format.

Reason: In release 1.18.0.0 (1I00) the data type for <modification_date> was changed from ASCII_Date_YMD to ASCII_Date_Time_YMD. However for backwards compatibility, the value for <modification_date>that is written to the Product_XML_Schema label must remain of type ASCII_Date_YMD. The data type ASCII_Date_Time_YMD allows for values of type ASCII_Date_YMD.

Resolves #650

## ⚙️ Test Data and/or Report
During I&T, the values of <modification_date> should validate under all versions of the IM prior to 1.18.0.0 (1I00) .

### CODE REVIEW

**Comment by jordanpadams** [comment]
@jshughes before making any more updates to your local repo, I would make sure your main branch is up to date with the main branch on GitHub. there are lots of weird merges that appear to be happening

**Comment by jshughes** [comment]
@jordanpadams Before I create any new branch, I always do a pull on main. For this build, I switched from GitHub Desktop to Eclipse Git so there is a new learning curve. @tloubrieu-jpl can we schedule a few minutes to review my process?

**Comment by jordanpadams** [comment]
@jshughes sounds good. I will also ping the team to see if anyone else can help.

**Comment by tloubrieu-jpl** [comment]
@jshughes I will schedule something at 2pm, PDT today

**Comment by tloubrieu-jpl** [comment]
@jshughes Actually I made it 9:30 tomorrow since you were busy on your calendar.

**Pull request merged**
