### PR TITLE
Update configs to use http: instead of https: for namespace URLs

### LINKED ISSUE #834: emrsp namespaces are configured to be produced as https:
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

When I run LDD_Tool on and rsp ingest file the dictionary is created with an https namespace instead of http

### 🕵️ Expected behavior

I expect something like http://psa.esa.int/psa/emrsp/rm/rls/v1 instead I get  https://psa.esa.int/psa/emrsp/rm/rls/v1. This appears to affect all rover (emrsp) based namespaces. Unfortunately I can't upload a .xml file to I renamed to .txt for the upload.
[lddingest_workshop_answer_1.0.txt](https://github.com/user-attachments/files/17660661/lddingest_workshop_answer_1.0.txt)

### 📜 To Reproduce

```bash
1.
2.
3.
...
```

### 🖥 Environment Info

```bash
- Version of this software [e.g. vX.Y.Z]
- Operating System: [e.g. MacOSX with Docker Desktop vX.Y]
...
```

### 📚 Version of Software Used

_No response_

### 🩺 Test Data / Additional context

_No response_

### 🦄 Related requirements

🦄 #xyz

### ⚙️ Engineering Details

_No response_

### 🎉 Integration & Test

_No response_

### PR DESCRIPTION
**Pull request by jordanpadams**
Per #834, base namespaces, we have standardized on using `http:` here.

Resolves #834

### CODE REVIEW

**Comment by jordanpadams** [comment]
@jshughes can you test that these updates are OK?

**Comment by jshughes** [comment]
@jordanpadams I ran three tests, common 1N00, juice 1N00, and juice 1J00. All passed. I did notice https://psa.esa.int/psa/mission/juice/v1 and assume that for ESA no change was expected.

**Comment by jordanpadams** [comment]
@jshughes which config do you see this in for JUICE? I just pinged PSA on the ticket, but I think we want to make this change for all PSA namespaces.

**Comment by jshughes** [comment]
@jordanpadams I created a new branch off my 241106_Incorrect_Schematron_External_Products branch - originally a branch off main, and replaced all "nameSpaceURLs=https://pds.nasa.gov/pds4/" in the config.properties file. The PSA, ... entries were not changed for my testing.

**Comment by jordanpadams** [comment]
Per comments on the issue, we are good to merge this change.

**Pull request merged**
