### PR TITLE
Update to support for open jdk17

### LINKED ISSUE #744: LDDTool producing invalid XSD for Voyager LDD
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

Generated LDD from ldd-vgr repo output invalid XSD

### 🕵️ Expected behavior

I expected valid XSD

### 📜 To Reproduce

```
lddtool -lpJ PDS4_VGR_IngestLDD.xml
```

Open XSD and notice it is invalid.

> The element type "xs:documentation" must be terminated by the matching end-tag "</xs:documentation>".

### 🖥 Environment Info
Any

### 📚 Version of Software Used

v14.3.0

### 🩺 Test Data / Additional context

[PDS4_VGR_IngestLDD.xml.txt](https://github.com/NASA-PDS/pds4-information-model/files/14844348/PDS4_VGR_IngestLDD.xml.txt)

### 🦄 Related requirements

Blocking https://github.com/pds-data-dictionaries/ldd-vgr/pull/14

### ⚙️ Engineering Details

_No response_

### LINKED ISSUE #746: JDK17 issue re-introduced bug per #733
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

When I tried to generate an LDD with the latest code on main, I get the same error as those associated with #733 

### 🕵️ Expected behavior

I expected LDDTool to execute successfully.

### 📜 To Reproduce

```bash
$ tests/smoke-tests.sh
...
Test 1: ldd-template
Cloning into 'ldd-repo'...
remote: Enumerating objects: 1833, done.
remote: Counting objects: 100% (860/860), done.
remote: Compressing objects: 100% (406/406), done.
remote: Total 1833 (delta 622), reused 599 (delta 441), pack-reused 973
Receiving objects: 100% (1833/1833), 1.12 MiB | 1.89 MiB/s, done.
Resolving deltas: 100% (1048/1048), done.
debug DMDocument HERE
debug DMDocument -0- sysDataHome:/Users/jpadams/proj/pds/pdsen/workspace/pds4-information-model/lddtool-pkg/lddtool-14.5.0-SNAPSHOT/Data

>>  ERROR SetMasterAttrXMLBaseDataTypeFromDataType - Data Type is missing - lAttr.identifier:0001_NASA_PDS_1.pds.Activity.pds.activity_type
>>  ERROR SetMasterAttrXMLBaseDataTypeFromDataType - Data Type is missing - lAttr.valueType:TBD_value_type
>>  ERROR SetMasterAttrXMLBaseDataTypeFromDataType - Data Type is missing - lAttr.identifier:0001_NASA_PDS_1.pds.Activity.pds.description
>>  ERROR SetMasterAttrXMLBaseDataTypeFromDataType - Data Type is missing - lAttr.valueType:TBD_value_type
>>  ERROR SetMasterAttrXMLBaseDataTypeFromDataType - Data Type is missing - lAttr.identifier:0001_NASA_PDS_1.pds.Activity.pds.title
>>  ERROR SetMasterAttrXMLBaseDataTypeFromDataType - Data Type is missing - lAttr.valueType:TBD_value_type
>>  ERROR SetMasterAttrXMLBaseDataTypeFromDataType - Data Type is missing - lAttr.identifier:0001_NASA_PDS_1.pds.Agent.pds.agent_type
>>  ERROR SetMasterAttrXMLBaseDataTypeFromDataType - Data Type is missing - lAttr.valueType:TBD_value_type
>>  ERROR SetMasterAttrXMLBaseDataTypeFromDataType - Data Type is missing - lAttr.identifier:0001_NASA_PDS_1.pds.Agent.pds.description
>>  ERROR SetMasterAttrXMLBaseDataTypeFromDataType - Data Type is missing - lAttr.valueType:TBD_value_type
>>  ERROR SetMasterAttrXMLBaseDataTypeFromDataType - Data Type is missing - lAttr.identifier:0001_NASA_PDS_1.pds.Agent.pds.title
>>  ERROR SetMasterAttrXMLBaseDataTypeFromDataType - Data Type is missing - lAttr.valueType:TBD_value_type
>>  ERROR SetMasterAttrXMLBaseDataTypeFromDataType - Data Type is missing - lAttr.identifier:0001_NASA_PDS_1.pds.ChangeLog.pds.%3ANAME
```
```


### 🖥 Environment Info

_No response_

### 📚 Version of Software Used

_No response_

### 🩺 Test Data / Additional context

_No response_

### 🦄 Related requirements

_No response_

### ⚙️ Engineering Details

_No response_

### PR DESCRIPTION
**Pull request by jshughes**
1. Cloned repository and reapplied changes for Update to support for open jdk17
2. Fixed ERROR 11179

Resolves #746

### CODE REVIEW

**Comment by jshughes** [comment]
@jordanpadams It looks like the build failed. I also am having trouble with my local maven build. However I wanted to see if I could get the working code into the repository. (Note, I had to clone and then apply my changes a third time after my local repository was corrupted.)  My problem now is that that I need a Maven expert to help me debug the Maven build.

**Comment by jordanpadams** [comment]
@jshughes can you post the errors you are seeing in maven?

**Comment by jordanpadams** [comment]
@jshughes also, the jdk17 updates were already merged to main, so any updates on this branch are actually for fixing the bugs associated with it.

**Comment by jordanpadams** [comment]
@jshughes per #744, I am still getting this error in Oxygen:

Screenshot 2024-04-02 at 3 27 40 PM

**Comment by jshughes** [comment]
@jordanpadams Re: "per https://github.com/NASA-PDS/pds4-information-model/issues/744, I am still getting this error in Oxygen"

Yes, the fix for that bug is queued. I am working on it now. My successful VGR tests used the "doctored" Ingest_LDD files.

Re: "the jdk17 updates were already merged to main, so any updates on this branch are actually for fixing the bugs associated with it"

Great, I have been trying to establish a baseline. I will proceed from here.

**Comment by jshughes** [comment]
@jordanpadams Re: can you post the errors you are seeing in maven?

C:\Users\jshughes\git\pds4-information-model>02_RunMavenInstall.bat

C:\Users\jshughes\git\pds4-information-model>"C:\Program Files\Maven\apache-maven-3.8.7"\bin\mvn install
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] PDS4 Information Model                                             [pom]
[INFO] Model DM-Document Maven Plugin                            [maven-plugin]
[INFO] Model Ontology                                                     [jar]
[INFO] Local Data Dictionary Tool                                         [pom]
[INFO]
[INFO] -------------------------< gov.nasa.pds:model >-------------------------
[INFO] Building PDS4 Information Model 14.5.0-SNAPSHOT                    [1/4]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-install-plugin:3.1.0:install (default-install) @ model ---
[INFO] Installing C:\Users\jshughes\git\pds4-information-model\pom.xml to C:\Users\jshughes\.m2\repository\gov\nasa\pds\model\14.5.0-SNAPSHOT\model-14.5.0-SNAPSHOT.pom
[INFO]
[INFO] ----------------< gov.nasa.pds.model:model-dmdocument >-----------------
[INFO] Building Model DM-Document Maven Plugin 14.5.0-SNAPSHOT            [2/4]
[INFO] ----------------------------[ maven-plugin ]----------------------------
[INFO]
[INFO] --- buildnumber-maven-plugin:3.1.0:create (default) @ model-dmdocument ---
[INFO] Storing buildNumber: 2024-04-02 17:32:26 at timestamp: 1712093546351
[WARNING] Cannot get the branch information from the git repository:
Detecting the current branch failed: 'git' is not recognized as an internal or external command,
operable program or batch file.

[INFO] Executing: cmd.exe /X /C "git rev-parse --verify HEAD"
[INFO] Working directory: C:\Users\jshughes\git\pds4-information-model\model-dmdocument
[INFO] Storing scmBranch: UNKNOWN_BRANCH
[INFO]
[INFO] --- maven-plugin-plugin:3.6.4:helpmojo (help-goal) @ model-dmdocument ---
[INFO] Using 'UTF-8' encoding to read mojo source files.
[INFO] java-javadoc mojo extractor found 0 mojo descriptor.
[INFO] ant mojo extractor found 0 mojo descriptor.
[INFO] bsh mojo extractor found 0 mojo descriptor.
[INFO] java-annotations mojo extractor found 0 mojo descriptor.
[INFO]
[INFO] --- maven-resources-plugin:3.3.1:resources (default-resources) @ model-dmdocument ---
[INFO] skip non existing resourceDirectory C:\Users\jshughes\git\pds4-information-model\model-dmdocument\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ model-dmdocument ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 98 source files to C:\Users\jshughes\git\pds4-information-model\model-dmdocument\target\classes
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for PDS4 Information Model 14.5.0-SNAPSHOT:
[INFO]
[INFO] PDS4 Information Model ............................. SUCCESS [  0.189 s]
[INFO] Model DM-Document Maven Plugin ..................... FAILURE [  3.066 s]
[INFO] Model Ontology ..................................... SKIPPED
[INFO] Local Data Dictionary Tool ......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.371 s
[INFO] Finished at: 2024-04-02T17:32:28-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project model-dmdocument: Fatal error compiling: invalid flag: --release -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :model-dmdocument
'cmd' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\jshughes\git\pds4-information-model>

**Comment by jordanpadams** [comment]
Closing fofr #749

**Pull request merged**
