### PR TITLE
Added micro amps and nano amps to units of current

### LINKED ISSUE #753: Allow micro amps and nano amps as units of current
### 🦄 Parent SCR

NASA-PDS/PDS4-CCB#16

### 💡 SCR Summary

ExoMars TGO has an instrument where current is measured in nano amps. However the standard only allows current to be expressed in amps or milliamps.

### PR DESCRIPTION
**Pull request by jshughes**
CCB-16: Allow micro amps and nano amps as units of current

Added the following units to Units_of_Current
- microA - The abbreviated unit for Units_of_Current is microA
- nA - The abbreviated unit for Units_of_Current is nA

## ⚙️ Test Data and/or Report
 -Schema snippet-
    <xs:simpleType name="Units_of_Current">
      <xs:restriction base="xs:string">
        <xs:enumeration value="A"></xs:enumeration>
        <xs:enumeration value="mA"></xs:enumeration>
        <xs:enumeration value="microA"></xs:enumeration>
        <xs:enumeration value="nA"></xs:enumeration>
      </xs:restriction>
    </xs:simpleType>

Resolves #753 
Refs NASA-PDS/PDS4-CCB#16

### CODE REVIEW

**Comment by jshughes** [comment]
@jordanpadams This pull request has an error and needs to be withdrawn. Should I just "Close with comment" or do you prefer a different method?

**Comment by jordanpadams** [comment]
@jshughes if you plan to just make changes to this branch, you can leave it open and [just switch it draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request#converting-a-pull-request-to-a-draft)

**Comment by jshughes** [comment]
@jordanpadams It seems that a merge of two or more changes involving protege files might not work as expected. Please deprecate this PR.

Background: Two Build 15.0 SCRs required simple changes to the Protege files. I was able to use Protege to make the changes directly to the files in Git. However each SCR had its own branch. Before merging, I noticed that the recorded changes in one of the branches involved many rows that I had not directly changed.  The Protege save function seems to reorder the rows in the class/attribute definition file. I assume that this could cause problems in a merge.

Two alternative options seem to be 1) do separate PRs so that the second branch is off of an updated main, or 2) include multiple changes in a single branch. This time around I am using separate PRs.

**Comment by jordanpadams** [comment]
@jshughes copy that.

**Pull request closed without merging**
